### ISSUE TITLE
Compatibility issue with Octave

### ISSUE THREAD

**Issue by xorxx** [LiorBanai/Hdf5DotnetWrapper#26]
We wrote a HDF5 file with DotnetWapper but reading this file in octave failed. Error message in Octave was:
```
>> d=load('hdf5file.mat')
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 0:
  #000: /release/mxe-octave-w64-64/tmp-hdf5/hdf5-1.8.14/src/H5Dio.c line 173 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: /release/mxe-octave-w64-64/tmp-hdf5/hdf5-1.8.14/src/H5Dio.c line 425 in H5D__read(): unable to set up type info
    major: Dataset
    minor: Unable to initialize object
  #002: /release/mxe-octave-w64-64/tmp-hdf5/hdf5-1.8.14/src/H5Dio.c line 957 in H5D__typeinfo_init(): unable to convert between src and dest datatype
    major: Dataset
    minor: Feature is unsupported
  #003: /release/mxe-octave-w64-64/tmp-hdf5/hdf5-1.8.14/src/H5T.c line 4532 in H5T_path_find(): no appropriate function for conversion path
    major: Datatype
    minor: Unable to initialize object
error: load: error while reading hdf5 item Description
```

Any hint what is going wrong?

Thanks!

**Comment by LiorBanai** [comment]
Hi,
Which version of Hdf5DotnetWrapper are you using?
can you share example of the code you are using to write the dataset that is problematic?
is the data viewable in hdfview?

**Comment by LiorBanai** [comment]
btw,
it seems almost exactly like https://forum.hdfgroup.org/t/errors-comparing-two-h5-files/4028

**Comment by xorxx** [comment]
We are using the current version of Hdf5DotnetWrapper. We will have a look on the file with hdfview. I am not the programmer so I have to ask for a code sample but I could share the problematic data file.
In the octave forum I found a hint that octave tends not to read foreign HDF5 files. This could also be a reason for our problem. But the message in hdfgroup forum looks in deed very similar to our problem. We will have a look for it on monday.

**Comment by LiorBanai** [comment]
Ok good.
If you can share the file itself it will be great to further investigate this (unless there is sensitive data inside the file).

**Comment by xorxx** [comment]
I just checked our file with the HDF5Viewer from HDFGroup and found no errors. This points clearly to a Problem on octave side as you can see in the [octave bug tracker issue 56148](https://savannah.gnu.org/bugs/index.php?56148)

**Comment by LiorBanai** [comment]
It could be incompatible data types. I would try to check one by one which is problematic by creating the file in steps until the specific data type is found. Strings could also be an issue.

**Comment by xorxx** [comment]
Thank you! I am closing this issue.
